version: '3'
services:
  app:
    image: gihan4/projectapp:1.0
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
  db:
    # from Docker Hub
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db_prices
      MYSQL_USER: gihanroey
      MYSQL_PASSWORD: roro123
      MYSQL_ROOT_PASSWORD: roro123
    volumes:
      # stored in the container
      - db-data:/var/lib/mysql
      - ./database/create_prices_table.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  # data written to the MySQL database will be stored within the volume
  db-data:
